# Generated by Django 2.1.5 on 2019-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190404_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='img_Prodect'),
            preserve_default=False,
        ),
    ]
